### ISSUE TITLE
Only the first code block renders highlighting

### ISSUE THREAD

**Issue by TheYorkshireDev** [if-Team/origami#11] opened 2018-03-30 15:31 UTC
Since Chrome version 61, most code blogs with associated syntax highlighting do not render correctly.

The first one works but any subsequent code blocks do not render. See below:

![screen shot 2018-03-30 at 16 19 15](https://user-images.githubusercontent.com/30004860/38142921-24b0b40e-3436-11e8-98e0-680b150e3c85.png)

After some research the issue is with Chrome (and I suspect other browsers now) adding a clipboard attribute to the `window` object. [This](https://github.com/PrismJS/prism/issues/1181) thread on **prismjs** issue explains it all.

We need to update the version of **prismjs** to at least `1.8.3` although I suspect this will break the webpack build.

**Comment by HelloWorld017** [comment] 2018-03-30 15:34
I cannot reproduce it at chrome 65 [Link](http://blog.khinenw.tk/css-center-aligning/).

**Comment by TheYorkshireDev** [comment] 2018-03-30 16:24
@HelloWorld017 thats interesting your page loads fine for me too in Chrome 65, but any posts I create have the issue.

Even though you cannot reproduce error, I still think it is a valid issue even the guy who maintains the clipboard NPM package has acknowledged it and updated clipboardJS in the last month. See https://github.com/zenorocha/clipboard.js/issues/468#issuecomment-369486055 so we should maybe update that dependency too to pull in his fix.

Out of curiosity are you running Ghost 0.11.x or 1.0?

**Comment by HelloWorld017** [comment] 2018-03-30 16:26
I am running 2.0.2-beta on Ghost 1.0

**Comment by HelloWorld017** [comment] 2018-03-30 16:27
It was built about 8 monthes ago.

**Comment by TheYorkshireDev** [comment] 2018-03-30 16:44
@HelloWorld017 I have just looked at updating **ClipboardJS** to the latest version `2.0.0`, but I feel there is little use at the moment because the version of **PrismJS** still uses `1.7.1`. 

We could update **PrismJS** to the latest version but that would incur lots of component renames just like the `prism-jade` -> `prism-pug` in PRs #12 & #13 and that deserves a PR of it's own.

**Comment by HelloWorld017** [comment] 2018-04-02 11:13
Merged #13 😆

**Closed as completed by HelloWorld017** 2018-04-02 11:13 UTC
